services:
  airflow:
    image: apache/airflow:2.10.2-python3.11
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG
      - _PIP_ADDITIONAL_REQUIREMENTS=psycopg2-binary
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin123 --firstname Admin --lastname User --role Admin --email admin@example.com &&
               airflow standalone"